### ISSUE TITLE
Expose properties to make it more customizable

### ISSUE THREAD

**Issue by ManueGE** [matmartinez/MMNumberKeyboard#17]
Hi! I really love this tool, since I knew it I use it over and over, so thanks for it!

The only thing I miss is some lack of customization. For example, if I want to change manually the return button color, or the decimal separator, or other kind of things. 

I think it shouldn't be difficult to expose some properties in the header file (the `dictionaryButton` to have full access to all buttons, for instance) to make it possible. 

Do you think this is a good idea? I could prepare a pull request if you want.

**Comment by matmartinez** [comment]
Hi ManueGE, thank you for the kind words. I'm happy you found this little project useful! I'll try my best to answer your questions:

#### 1. Customizing the return button color

The `MMNumberKeyboard` object is, after all, just a view. You can set a tint color (`.tintColor` is inherited from `UIView`) to make that happen. 

As with any other window, the system will create another window for the keyboard. As a result, the return key won't be "tinted" with the color that you've chosen for your application's window. 

Note that Apple does this for a reason. Keyboards are consistent across all apps. You'll potentially be making harder for your users to distinguish the boundaries between the keyboard and your application. To make this more clear, ask yourself: If the "Done" button of the system keyboard is blue on all applications, why this should be different?

#### 2. Providing a custom decimal separator
First, there's an `.allowsDecimalPoint` property if you don't need this key. 

The customization of this property is entirely up to the user's locale, just like the system keyboard. That's because the decimal separator varies for each country. You can initialize the keyboard with a custom `NSLocale` object of your own, for example, if you're dealing with multiple currencies in a single application.


#### 3. Customizing the keys' appearance

Since a couple of releases ago and by popular request, I added customization options for the return key:

```
/**
 *  The visible title of the Return key.
 *
 *  @note The default visible title of the Return key is “Done”.
 */
@property (copy, nonatomic) NSString *returnKeyTitle;

/**
 *  The button style of the Return key.
 *
 *  @note The default value of this property is @c MMNumberKeyboardButtonStyleDone.
 */
@property (assign, nonatomic) MMNumberKeyboardButtonStyle returnKeyButtonStyle;
```

It's also possible to replace the key that dismisses the keyboard:

```
/**
 *  Configures the special key with an image and an action block.
 *
 *  @param image   The image to display in the key.
 *  @param handler A handler block.
 */
- (void)configureSpecialKeyWithImage:(UIImage *)image actionHandler:(dispatch_block_t)handler;
```

And I believe that's as far as key customization will get. 

Just an example: The reason why "styles" are chosen instead of "custom colors" is first, for simplicity, and second, because people will inevitably pick the worst possible colors combinations resulting in terrible designs. And you can tell it's the same problem if you allow custom shapes, layout, etc. 

I've already rejected pull requests that attempt to add this much customization, and I'm simply not willing to let that happen. Remember that after all, *this is just a keyboard*. It mimics the system appearance because *it's supposed to do so*.  

I hope this makes any sense. 

Matías.
