### ISSUE TITLE
Multiple decimal points!

### ISSUE THREAD

**Issue by ServicePal** [matmartinez/MMNumberKeyboard#24]
Seems a bit odd to me that you are allowed to enter the decimal point multiple times. I am missing something?

**Comment by matmartinez** [comment]
Hi @ServicePal,

Yes, this is the expected behavior. It is your responsibility lo limit the characters that are being inserted, if that's what you want. 

This works exactly as the system's `.decimalPad` keyboard type, or any other keyboard for that matter (even real life ones! 🙂). 

Take a look at the `-numberKeyboard:shouldInsertText:` delegate method. I would recommend you to check against a `NSCharacterSet` and return `NO` when needed. 

Hope it makes sense. I'll be closing this issue. 
Matias.
