### ISSUE TITLE
Floating keyboard on iPad

### ISSUE THREAD

**Issue by EddyVerbruggen** [matmartinez/MMNumberKeyboard#33]
Hi! Thanks for the great work 👍 

I'm using (a fork of) your library in [this NativeScript plugin](https://github.com/EddyVerbruggen/nativescript-numeric-keyboard) and in a few apps. It works brilliantly.

One of my clients asked whether or not it would be possible to make those grey blocks to the left an right of the keyboard (see the screenshot below) transparent, so it would make the keyboard "float". I've tried a few things myself but couldn't figure out how to do it, so I was hoping anyone here would have a suggestion.

![simulator screen shot - ipad pro 9 7 inch - 2017-10-05 at 14 55 46](https://user-images.githubusercontent.com/1426370/31319099-bc1f2aca-ac5d-11e7-83fb-a1bfbe0eecc2.png)

**Comment by matmartinez** [comment]
Hi there @EddyVerbruggen!

Wow, it seems that fork must be doing something _really_ weird to display the keyboard incorrectly, because that's not the appearance of MMNumberKeyboard on an iPad. 

I'm sorry, but I have no knowledge of what NativeScript is or what that your fork is doing with the code. Supporting this is out of the scope of this project.

I'd encourage you to use MMNumberKeyboard with UIKit directly.

Good luck! 😉 
Matías.

**Comment by EddyVerbruggen** [comment]
Haha yeah that’s why I forked it: to alter the appearance on iPad because a customer liked it better that way ;)

Thanks for your answer!
