### ISSUE TITLE
Enhancement: change colours easily?

### ISSUE THREAD

**Issue by vincentneo** [matmartinez/MMNumberKeyboard#37]
Can we have the keyboard button's colour change easily? or is there already a way to do so easily?

**Comment by matmartinez** [comment]
Hi @vincentneo,

By default, input views inherit the default tint color of the system. I believe this behavior is intentional and correct, as it makes keyboards look consistent no matter which app you’re using. 

If you want to go fight _the system_, you can set your own tint color just like on any `UIView`:

```swift
keyboard.tintColor = UIColor.purple
```

Hope it helps,
Matías.

**Comment by vincentneo** [comment]
Alright! Thank You! Just an occasion where I needed to 'fight' with the system! thanks for the help!
