### ISSUE TITLE
Keyboard only works with first UITextField

### ISSUE THREAD

**Issue by mikeytriology** [matmartinez/MMNumberKeyboard#6]
Hi,

I have multiple numeric textfields. The keyboard works normally with the first field I click on. On the second field pressing any key has no effect. Ie, numbers aren't placed in textfield and I can't lower (hide) the keyboard. This is how I'm setting up the keyboard:

    MMNumberKeyboard *keyboardNoDecimal = [[MMNumberKeyboard alloc] initWithFrame:CGRectZero];
    keyboardNoDecimal.allowsDecimalPoint = NO;
    keyboardNoDecimal.delegate = self;
    
    MMNumberKeyboard *keyboardDecimal = [[MMNumberKeyboard alloc] initWithFrame:CGRectZero];
    keyboardDecimal.allowsDecimalPoint = YES;
    keyboardDecimal.delegate = self;

    self.hundredsCountTextField.inputView = keyboardNoDecimal;
    self.fiftiesCountTextField.inputView = keyboardNoDecimal;
    self.twentiesCountTextField.inputView = keyboardNoDecimal;
    self.tensCountTextField.inputView = keyboardNoDecimal;
    self.fivesCountTextField.inputView = keyboardNoDecimal;
    
    self.eodFloatTextField.inputView = keyboardDecimal;
    self.coinsTotalTextField.inputView = keyboardDecimal;
    self.eftposTotalTextField.inputView = keyboardDecimal;

Am I doing it wrong?

Thanks in advance

Mikey

**Comment by matmartinez** [comment]
I'm afraid you're moving the same keyboard from one view to another each time you assign it to another text field. A quick StackOverflow search can confirm this is the expected behavior when using any UIView as an inputView. 

You will need an instance for each text field. I suggest you subclass UITextField so you don't have to repeat yourself so much. 

Cheers!

**Comment by mikeytriology** [comment]
Awesome! Thanks!
