### ISSUE TITLE
Allow disabling Done button

### ISSUE THREAD

**Issue by ZevEisenberg** [matmartinez/MMNumberKeyboard#7]
The Done button should be able to be disabled, either based on delegate methods, a direct property, or a `UITextField`-like "auto-enable Return key" mode. In my use case, I'm using MMNumberKeyboard to fill in a single field, and I don't want the Go button to be enabled until the text field is non-empty.

**Comment by matmartinez** [comment]
Hello Zev, this would indeed make a great feature.

This is a tricky thing to do using the `<UIKeyInput>` protocol, because we'll need to observe changes made by the view itself (for example, the text could be changed by other code while the keyboard is active). 

I'll investigate more about this and update the issue. Thanks!

**Comment by alfredcc** [comment]
How it's going?

**Comment by ZevEisenberg** [comment]
Bump - @matmartinez I'd love to add this feature, but I don't see how to use `UIKeyInput` to get there. Do you have an idea of a starting point? I should be able to take it from there.

**Comment by matmartinez** [comment]
Hey guys! I'll try to understand how UIKit handles this internally with a dissembler. Will update this issue with the results :)

**Comment by matmartinez** [comment]
@ZevEisenberg finally solved this using the `<UITextInputDelegate>` protocol. This is not enabled by default, but it is quite simple to set up:

```objc
keyboard.enablesReturnKeyAutomatically = YES;
```

Cheers!

**Comment by ZevEisenberg** [comment]
Hooray! 🎉
